server:
  port: 8080


datasource:
  tenants:
    india:
      url: jdbc:mysql://localhost:3306/india_db?useSSL=false&serverTimezone=UTC
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver

    china:
      url: jdbc:mysql://localhost:3306/china_db?useSSL=false&serverTimezone=UTC
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
